# Generated by Django 5.2.7 on 2025-11-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppcx_app', '0012_alter_image_camera'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='rotation',
            field=models.IntegerField(default=0, help_text='Rotation in degrees (0, 90, 180, 270)'),
        ),
    ]
