# Generated by Django 5.2.7 on 2025-11-25 11:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ppcx_app", "0016_sync_collapse_with_db"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collapse",
            options={"managed": True},
        ),
        migrations.AddField(
            model_name="dic",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dic",
            name="ensemble_image_pairs",
            field=models.JSONField(
                blank=True,
                help_text="List of {'master': image_id, 'slave': image_id} pairs used for ensemble correlation",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="dic",
            name="ensemble_size",
            field=models.IntegerField(
                blank=True, help_text="Number of image pairs in the ensemble", null=True
            ),
        ),
        migrations.AlterField(
            model_name="dic",
            name="use_ensemble_correlation",
            field=models.BooleanField(
                default=False, help_text="Whether ensemble correlation was used"
            ),
        ),
    ]
