# Generated by Django 5.2.7 on 2025-11-25 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppcx_app', '0017_alter_collapse_options_collapse_date_dic_created_at_and_more'),
    ]

    operations = [
    ]
