# Generated by Django 5.2.7 on 2025-11-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppcx_app', '0018_collapse_date_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='collapse',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
