# Generated by Django 5.2.7 on 2025-11-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppcx_app', '0019_collapse_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='collapse',
            name='type',
            field=models.IntegerField(blank=True, choices=[], help_text='Type of collapse event (1=disaggregation, 2=slab, 3=water outburst)', null=True),
        ),
    ]
