# Generated by Django 5.2.7 on 2025-11-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppcx_app', '0021_alter_collapse_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='gsd',
            field=models.FloatField(blank=True, help_text='Average ground Sampling Distance in cm/pixel', null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='easting',
            field=models.FloatField(blank=True, help_text='Easting coordinate in meters (EPSG 32632)', null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='elevation',
            field=models.FloatField(blank=True, help_text='Elevation in meters (EPSG 32632)', null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='epsg_code',
            field=models.IntegerField(default=32632, help_text='EPSG code for the coordinate reference system'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='northing',
            field=models.FloatField(blank=True, help_text='Northing coordinate in meters (EPSG 32632)', null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='pixel_size_um',
            field=models.FloatField(blank=True, help_text='Physical pixel size in micrometers', null=True),
        ),
        migrations.AlterField(
            model_name='collapse',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, 'Disaggregation'), (2, 'Slab'), (3, 'Water outburst')], help_text='Type of collapse event', null=True),
        ),
    ]
