# Generated by Django 5.2.7 on 2025-11-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppcx_app', '0022_camera_gsd_alter_camera_easting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dic',
            name='with_inversion',
            field=models.BooleanField(default=False, help_text='Whether time-series inversion was applied to refine DIC results'),
        ),
    ]
