# Generated by Django 5.2.7 on 2025-11-28 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppcx_app', '0023_dic_with_inversion'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dic',
            name='different_timestamps',
        ),
        migrations.RemoveConstraint(
            model_name='dic',
            name='unique_image_pair_paths_dt_hours',
        ),
    ]
