# Generated by Django 5.2.7 on 2025-11-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ppcx_app", "0024_remove_dic_different_timestamps_and_more"),
    ]

    operations = [
        # Operation 1: Rename acquisition_timestamp to datetime (already done in DB)
        migrations.RenameField(
            model_name="image",
            old_name="acquisition_timestamp",
            new_name="datetime",
        ),
        # Operation 2: Add acquisition_timestamp back as generated column (already done in DB)
        migrations.AddField(
            model_name="image",
            name="acquisition_timestamp",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                null=True,
                db_comment="Deprecated: use datetime instead",
            ),
        ),
    ]
