# Generated by Django 5.2.7 on 2025-11-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppcx_app', '0025_rename_acquisition_timestamp_to_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='datetime',
            field=models.DateTimeField(db_column='datetime'),
        ),
    ]
