# Generated by Django 5.2.7 on 2025-11-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppcx_app', '0026_alter_image_datetime'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='image',
            name='unique_camera_timestamp',
        ),
        migrations.RemoveIndex(
            model_name='image',
            name='ppcx_app_im_acquisi_b2d820_idx',
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['datetime'], name='ppcx_app_im_datetim_ad689b_idx'),
        ),
        migrations.AddConstraint(
            model_name='image',
            constraint=models.UniqueConstraint(fields=('camera', 'datetime'), name='unique_camera_timestamp'),
        ),
    ]
