# Generated by Django 5.2.7 on 2025-11-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppcx_app', '0028_altered_master_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='dic',
            name='dic_master_ts_idx',
        ),
        migrations.RemoveIndex(
            model_name='dic',
            name='dic_slave_ts_idx',
        ),
        migrations.AlterField(
            model_name='dic',
            name='result_file_path',
            field=models.CharField(blank=True, help_text='Path to the DIC results HDF5 file stored inside the server', max_length=1024, null=True),
        ),
    ]
