# Generated by Django 5.2.7 on 2025-12-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppcx_app', '0029_remove_dic_dic_master_ts_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='file_size_bytes',
            field=models.BigIntegerField(blank=True, db_index=True, editable=False, help_text='File size in bytes (auto-populated on save)', null=True),
        ),
    ]
